In [1]:
#IMPORTING LIBRARIES

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
#IMPORT DATA

df = pd.read_csv("/kaggle/input/cardiovascular-disease-dataset/cardio_train.csv")
df.head()

  id;age;gender;height;weight;ap_hi;ap_lo;cholesterol;gluc;smoke;alco;active;cardio
0              0;18393;2;168;62.0;110;80;1;1;0;0;1;0
1              1;20228;1;156;85.0;140;90;3;1;0;0;1;1
2              2;18857;1;165;64.0;130;70;3;1;0;0;0;1
3             3;17623;2;169;82.0;150;100;1;1;0;0;1;1
4              4;17474;1;156;56.0;100;60;1;1;0;0;0;0

In [3]:
df = pd.read_csv("/kaggle/input/cardiovascular-disease-dataset/cardio_train.csv",sep=';')
df.dropna(axis=0, inplace=True)

In [4]:
#Check null values
df.isnull().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [5]:
df = df.drop(['id'],axis=1)

In [6]:
df.head()

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [7]:
#NORMALISATION

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
num_vars = ['age','gender','height','weight','ap_hi','ap_lo']
df[num_vars] = scaler.fit_transform(df[num_vars])
df

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0.588076,1.0,0.579487,0.273684,0.016079,0.013550,1,1,0,0,1,0
1,0.730159,0.0,0.517949,0.394737,0.017934,0.014453,3,1,0,0,1,1
2,0.624003,0.0,0.564103,0.284211,0.017316,0.012647,3,1,0,0,0,1
3,0.528455,1.0,0.584615,0.378947,0.018553,0.015357,1,1,0,0,1,1
4,0.516918,0.0,0.517949,0.242105,0.015461,0.011743,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
69995,0.653659,1.0,0.579487,0.347368,0.016698,0.013550,1,1,1,0,1,0
69996,0.913899,0.0,0.528205,0.610526,0.017934,0.014453,2,2,0,0,1,1
69997,0.640186,1.0,0.656410,0.500000,0.020408,0.014453,3,1,0,1,0,1
69998,0.900736,0.0,0.553846,0.326316,0.017625,0.013550,1,2,0,0,0,1
69999,0.754317,0.0,0.589744,0.326316,0.016698,0.013550,2,1,0,0,1,0

In [8]:
#SPLITTING THE DATA

from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(df, train_size = 0.7, test_size = 0.3, random_state = 152)
y_train = df_train.pop('cardio')
x_train = df_train
y_test = df_test.pop('cardio')
x_test = df_test
x_train = x_train.T
y_train = y_train.T
x_test = x_test.T
y_test = y_test.T

**TRAINING THE DATA**

**LOGISTIC REGRESSION**

In [9]:
accuracies = {}
accuracies1 = {}
lr = LogisticRegression()
lr.fit(x_train.T,y_train.T)
acc = lr.score(x_train.T,y_train.T)*100
acc1 = lr.score(x_test.T,y_test.T)*100
accuracies['Logistic Regression'] = acc
accuracies1['Logistic Regression'] = acc1
print("Training Accuracy {:.2f}%".format(acc))
print("Testing Accuracy {:.2f}%".format(acc1))

Training Accuracy 64.93%
Testing Accuracy 64.39%

In [10]:
import math as mt
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

prediction = lr.predict(x_test.T)
#Training Accuracies
rmse = mt.sqrt(mean_squared_error(y_test.T, prediction)) 
print('Root mean square error', rmse) 
mse = (mean_squared_error(y_test, prediction)) 
print('Mean square error', mse) 
mae=mean_absolute_error(y_test, prediction)
print('Mean absolute error', mae)

Root mean square error 0.5967371599751754
Mean square error 0.3560952380952381
Mean absolute error 0.3560952380952381

**KNN**

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 2)  
# n_neighbors means k\n",
knn.fit(x_train.T, y_train.T)
prediction = knn.predict(x_test.T)
print("{} NN Training Score: {:.2f}%".format(2, knn.score(x_train.T, y_train.T)*100))
print("{} NN Testing Score: {:.2f}%".format(2, knn.score(x_test.T, y_test.T)*100))

2 NN Training Score: 78.26%
2 NN Testing Score: 56.40%

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn3 = KNeighborsClassifier(n_neighbors = 3)  
# n_neighbors means k\n",
knn3.fit(x_train.T, y_train.T)
prediction = knn3.predict(x_test.T)
print("{} NN Training Score: {:.2f}%".format(3, knn3.score(x_train.T, y_train.T)*100))
print("{} NN Testing Score: {:.2f}%".format(3, knn3.score(x_test.T, y_test.T)*100))

3 NN Training Score: 78.79%
3 NN Testing Score: 58.90%

In [13]:
rmse = mt.sqrt(mean_squared_error(y_test.T, prediction)) 
print('Root mean square error', rmse) 
mse = (mean_squared_error(y_test, prediction)) 
print('Mean square error', mse) 
mae=mean_absolute_error(y_test, prediction)
print('Mean absolute error', mae)

Root mean square error 0.6410556769519953
Mean square error 0.41095238095238096
Mean absolute error 0.41095238095238096

**DESCISION TREE**

In [14]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(max_depth=5)
dtc.fit(x_train.T, y_train.T)
acc = dtc.score(x_train.T, y_train.T)*100
acc1 = dtc.score(x_test.T, y_test.T)*100
accuracies['Decision Tree'] = acc
accuracies1['Decision Tree'] = acc1
print("Decision Tree Training Accuracy {:.2f}%".format(acc))
print("Decision Tree Testing Accuracy {:.2f}%".format(acc1))

Decision Tree Training Accuracy 73.45%
Decision Tree Testing Accuracy 73.04%

In [15]:
prediction = dtc.predict(x_test.T)
rmse = mt.sqrt(mean_squared_error(y_test.T, prediction)) 
print('Root mean square error', rmse) 
mse = (mean_squared_error(y_test, prediction)) 
print('Mean square error', mse) 
mae=mean_absolute_error(y_test, prediction)
print('Mean absolute error', mae)

Root mean square error 0.5192026854431981
Mean square error 0.2695714285714286
Mean absolute error 0.2695714285714286

**RANDOM FOREST**

In [16]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 1000,max_depth=5, random_state = 1)
rf.fit(x_train.T, y_train.T)
acc = rf.score(x_train.T,y_train.T)*100
acc1 = rf.score(x_test.T,y_test.T)*100
accuracies['Random Forest'] = acc
accuracies1['Random Forest'] = acc1
print("Random Forest Algorithm Training Accuracy Score : {:.2f}%".format(acc))
print("Random Forest Algorithm Testing Accuracy Score : {:.2f}%".format(acc1))

Random Forest Algorithm Training Accuracy Score : 73.27%
Random Forest Algorithm Testing Accuracy Score : 72.74%

In [17]:
prediction = rf.predict(x_test.T)
rmse = mt.sqrt(mean_squared_error(y_test.T, prediction)) 
print('Root mean square error', rmse) 
mse = (mean_squared_error(y_test, prediction)) 
print('Mean square error', mse) 
mae=mean_absolute_error(y_test, prediction)
print('Mean absolute error', mae)

Root mean square error 0.5220837371259792
Mean square error 0.2725714285714286
Mean absolute error 0.2725714285714286